---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g ember-cli
  - npm install -g phantomjs
  - npm install -g bower
  - npm install
  - npm install
  - bower install

script:
  - ember test
